version: '3.9'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN="<TOKEN>"
      - PING_INTERVAL_SECONDS=5;
      - FILE_SYNC_SECONDS=600;
      - DISCORD_STATS_UPDATE_SECONDS=10;
    volumes:
      - ./stats.json:/usr/src/app/stats.json
