name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate Docker Image Tag
      run: |
        echo "$(date +%s)" >> $DOCKER_TAG

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_IMAGE: ${{secrets.DOCKER_IMAGE}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo Cockc
        echo $DOCKER_TAG

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_IMAGE}}:$DOCKER_TAG
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_IMAGE}}:$DOCKER_TAG
